/**
 * This file was auto-generated by openapi-typescript.
 * Do not make direct changes to the file.
 */

export interface paths {
    "/api/health": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        /**
         * Report that the server is running, which wiki it is serving, and how fresh
         *     its index is.
         */
        get: operations["health"];
        put?: never;
        post?: never;
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/api/links/{slug}": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        /**
         * Both directions of a page's links.
         * @description The slug does not have to name a page that exists: asking about a wanted
         *     page returns what already points at it, which is what you want to see before
         *     deciding whether to write it.
         *
         *     Both directions come back together because that is how they are used — a
         *     page view shows its links and its backlinks at once, and one round trip
         *     beats two.
         */
        get: operations["links"];
        put?: never;
        post?: never;
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/api/move": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        get?: never;
        put?: never;
        /**
         * Move a page to a new slug.
         * @description Inbound links are left as they are. They become wanted pages, so a move
         *     shows up in the wiki's stats rather than rotting quietly.
         */
        post: operations["move_page"];
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/api/pages": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        /** List pages, without their bodies. */
        get: operations["list"];
        put?: never;
        /** Create a page. Fails if one already exists at that slug. */
        post: operations["create"];
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/api/pages/{slug}": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        /** Fetch a page, as markdown. */
        get: operations["read"];
        /** Create or wholly replace a page. */
        put: operations["replace"];
        post?: never;
        /** Delete a page. */
        delete: operations["delete"];
        options?: never;
        head?: never;
        /** Update some of a page, leaving the rest alone. */
        patch: operations["patch"];
        trace?: never;
    };
    "/api/reindex": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        get?: never;
        put?: never;
        /**
         * Rebuild the search index from the wiki directory.
         * @description The index holds nothing that is not already on disk, so this is always safe
         *     and never loses anything. It is the escape hatch for the one case
         *     incremental scanning can miss: an edit that leaves both mtime and size
         *     unchanged.
         */
        post: operations["reindex"];
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/api/render": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        get?: never;
        put?: never;
        /**
         * Render markdown to HTML without storing it.
         * @description `GET /api/pages/{slug}?render=true` renders what is *saved*, which is no use
         *     to an editor showing an unsaved draft. This renders whatever it is handed,
         *     through the same renderer, so a preview cannot disagree with what the page
         *     will look like once written. Rendering in the client instead would mean a
         *     second markdown implementation that does not know about wikilinks, and it
         *     would be wrong in exactly the places this wiki cares about.
         *
         *     Nothing is read or written, so this is safe to call on every keystroke.
         */
        post: operations["render_markdown"];
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/api/search": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        /** Search page titles and bodies. */
        get: operations["search"];
        put?: never;
        post?: never;
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/api/stats": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        /**
         * The wiki's meta-stats.
         * @description Orphans and wanted pages are the two most useful numbers here, and they are
         *     two sides of the same thing: pages nothing reaches, and reaches with nothing
         *     at the end. A wiki that branches chaotically accumulates both.
         */
        get: operations["stats"];
        put?: never;
        post?: never;
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/api/tags": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        /** Every tag in the wiki, with page counts. */
        get: operations["tags"];
        put?: never;
        post?: never;
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
}
export type webhooks = Record<string, never>;
export interface components {
    schemas: {
        CreatePage: {
            /**
             * @description Markdown body, without frontmatter.
             * @example # Async in Rust
             *
             *     Futures are lazy. See [[notes/rust/pinning]].
             */
            content?: string;
            /** @description Where the page will live. `409` if something is already there. */
            slug: components["schemas"]["Slug"];
            /**
             * @description Free-form; tags are whatever you have used elsewhere. `GET /api/tags`
             *     lists the ones already in play.
             * @example [
             *       "rust",
             *       "async"
             *     ]
             */
            tags?: string[];
            /**
             * @description Optional. Without it the title falls back to the body's first heading,
             *     then to the slug.
             * @example Async in Rust
             */
            title?: string | null;
        };
        ErrorDetail: {
            /**
             * @description Stable, machine-readable identifier for what went wrong.
             * @example page_not_found
             */
            code: string;
            /**
             * @description Context for correcting the request, when there is any. Where something
             *     was refused for being outside a fixed set, this names the values that
             *     would have worked.
             */
            details?: unknown;
            /**
             * @description Human-readable explanation. Prose; do not branch on it.
             * @example no page at notes/asnyc
             */
            message: string;
        };
        ErrorResponse: {
            /**
             * @description Every failure has this shape, whatever the status. Branch on
             *     `error.code`.
             */
            error: components["schemas"]["ErrorDetail"];
        };
        Health: {
            /**
             * Format: date-time
             * @description When the index was last reconciled with the wiki directory. Null if it
             *     has not been scanned yet.
             */
            last_indexed?: string | null;
            /**
             * @description Number of pages currently indexed.
             * @example 42
             */
            pages: number;
            /**
             * @description Always `"ok"` — a response at all is the liveness signal.
             * @example ok
             */
            status: string;
            /**
             * @description The running Rhizolog version.
             * @example 0.1.0
             */
            version: string;
            /**
             * @description Absolute path of the wiki directory being served.
             * @example /home/tim/wiki
             */
            wiki_root: string;
        };
        InboundLinkView: {
            /**
             * @description What the link says, when that differs from the target.
             * @example the async notes
             */
            display?: string | null;
            /**
             * @description `wiki` or `internal`. A page cannot be reached by an external link.
             * @example wiki
             */
            kind: string;
            /** @description The page that links here. */
            slug: components["schemas"]["Slug"];
            /**
             * @description Its title.
             * @example Async in Rust
             */
            title: string;
        };
        LinkTotalsView: {
            /**
             * @description Links leaving the wiki.
             * @example 2
             */
            external: number;
            /**
             * @description Links pointing at pages, whether or not those pages exist.
             * @example 9
             */
            internal: number;
            /**
             * @description Internal links whose target exists.
             * @example 8
             */
            resolved: number;
            /**
             * @description Internal links whose target has not been written yet.
             * @example 1
             */
            wanted: number;
        };
        LinkedPageView: {
            /**
             * @description How many pages link to it.
             * @example 3
             */
            referrers: number;
            slug: components["schemas"]["Slug"];
            /**
             * @description The page's effective title.
             * @example Async in Rust
             */
            title: string;
        };
        MovePage: {
            /** @description The page to move. `404` if there is nothing there. */
            from: components["schemas"]["Slug"];
            /** @description Where it goes. `409` if that slug is taken. */
            to: components["schemas"]["Slug"];
        };
        OutboundLinkView: {
            /**
             * @description The link's text, when it says something other than the target.
             * @example why pinning exists
             */
            display?: string | null;
            /**
             * @description `wiki` (`[[slug]]`), `internal` (a markdown link to a page), or
             *     `external`.
             * @example wiki
             */
            kind: string;
            /**
             * @description Whether this points at a page that exists. A `false` here is not an
             *     error — it is a wanted page.
             */
            resolved: boolean;
            /**
             * @description A slug for `wiki` and `internal` links, a URL for `external` ones.
             * @example notes/rust/pinning
             */
            target: string;
            /**
             * @description Title of the target page, when it exists.
             * @example Pinning
             */
            title?: string | null;
        };
        PageLinksResponse: {
            /** @description Whether the page itself exists. Links can point at pages that do not. */
            exists: boolean;
            /** @description Pages that link here — the backlinks. */
            inbound: components["schemas"]["InboundLinkView"][];
            /** @description Links this page makes, in document order, deduplicated per kind. */
            outbound: components["schemas"]["OutboundLinkView"][];
            /** @description The slug that was asked about. */
            slug: components["schemas"]["Slug"];
        };
        PageListResponse: {
            /**
             * @description The limit that was applied, after clamping.
             * @example 50
             */
            limit: number;
            /**
             * @description The offset that was applied.
             * @example 0
             */
            offset: number;
            /**
             * @description Bodies are never included here. When `fields` is given, each entry
             *     carries only the requested subset of these keys.
             */
            pages: components["schemas"]["PageSummary"][];
            /**
             * @description Total matching pages, not the number returned.
             * @example 128
             */
            total: number;
        };
        PageRefView: {
            slug: components["schemas"]["Slug"];
            /**
             * @description The page's effective title.
             * @example Async in Rust
             */
            title: string;
        };
        /** @description A page without its content. */
        PageSummary: {
            /**
             * Format: date-time
             * @description When the page was first written, falling back to the file's mtime.
             */
            created: string;
            /**
             * Format: int64
             * @description Size of the page's file on disk, in bytes.
             * @example 312
             */
            size: number;
            slug: components["schemas"]["Slug"];
            /**
             * @description The page's tags, in the order the frontmatter lists them.
             * @example [
             *       "rust",
             *       "async"
             *     ]
             */
            tags: string[];
            /**
             * @description The page's effective title: its frontmatter `title`, or failing that the
             *     body's first heading, or failing that the slug.
             * @example Async in Rust
             */
            title: string;
            /**
             * Format: date-time
             * @description The file's modification time.
             */
            updated: string;
        };
        /** @description A page and its content. */
        PageView: {
            /**
             * @description The page body as markdown, without its frontmatter. Title and tags are
             *     returned as fields above rather than left in the text, so an editor
             *     never has to reserialise YAML to change one of them.
             * @example # Async in Rust
             *
             *     Futures are lazy. See [[notes/rust/pinning]].
             */
            content: string;
            /**
             * Format: date-time
             * @description When the page was first written. Falls back to the file's mtime for
             *     pages written by hand, which never carried the field.
             */
            created: string;
            /**
             * @description The body rendered to HTML. Present only when `render=true` was asked
             *     for.
             *
             *     Raw HTML in the source is dropped rather than passed through — the
             *     markup does not appear in the output at all, escaped or otherwise. Links
             *     to pages come back as browsable `/pages/...` URLs.
             * @example <h1>Async in Rust</h1>
             *     <p>Futures are lazy. See <a href="/pages/notes/rust/pinning" data-wikilink="true">notes/rust/pinning</a>.</p>
             */
            html?: string | null;
            /**
             * Format: int64
             * @description Size of the page's file on disk, in bytes.
             * @example 312
             */
            size: number;
            slug: components["schemas"]["Slug"];
            /**
             * @description The page's tags, in the order the frontmatter lists them.
             * @example [
             *       "rust",
             *       "async"
             *     ]
             */
            tags: string[];
            /**
             * @description The page's effective title: its frontmatter `title`, or failing that the
             *     body's first heading, or failing that the slug.
             * @example Async in Rust
             */
            title: string;
            /**
             * @description Whether `title` was derived rather than stored — from the body's first
             *     heading, or failing that the slug.
             *
             *     This is what makes read-modify-write safe. Send a derived title back and
             *     it stops being derived: it is written into the frontmatter, and the
             *     heading it came from can never update it again. A client editing a page
             *     should send `null` for the title while this is true, and the editor in
             *     the dashboard leaves its title field empty for exactly that reason.
             */
            title_derived: boolean;
            /**
             * Format: date-time
             * @description The file's modification time.
             */
            updated: string;
        };
        /** @description A partial update. Omitted fields are left alone. */
        PatchPage: {
            /**
             * @description Replaces the whole body when present.
             * @example # Async in Rust
             *
             *     Futures are lazy. See [[notes/rust/pinning]].
             */
            content?: string | null;
            /**
             * @description Replaces the whole tag list when present.
             * @example [
             *       "rust",
             *       "async"
             *     ]
             */
            tags?: string[] | null;
            /**
             * @description Omit to leave the title unchanged; send `null` to clear it and fall
             *     back to the heading or slug.
             * @example Async in Rust
             */
            title?: string | null;
        };
        ReindexResponse: {
            /**
             * @description Pages on disk that could not be read, and so are not searchable.
             * @example 0
             */
            failed: number;
            /**
             * @description Pages read and written to the index.
             * @example 6
             */
            indexed: number;
            /**
             * @description Pages dropped because they are no longer on disk.
             * @example 0
             */
            removed: number;
            /**
             * @description Pages found on disk.
             * @example 6
             */
            scanned: number;
        };
        /** @description Markdown to render, with the context its links need. */
        RenderRequest: {
            /**
             * @description Markdown body, without frontmatter.
             * @example # Async in Rust
             *
             *     Futures are lazy. See [[notes/rust/pinning]].
             */
            content: string;
            slug?: null | components["schemas"]["Slug"];
        };
        /** @description Markdown rendered to HTML. */
        RenderedHtml: {
            /**
             * @description The rendered body. Raw HTML in the source is dropped rather than passed
             *     through, and links to pages come back as browsable `/pages/...` URLs.
             * @example <h1>Async in Rust</h1>
             *     <p>Futures are lazy. See <a href="/pages/notes/rust/pinning" data-wikilink="true">notes/rust/pinning</a>.</p>
             */
            html: string;
        };
        /** @description A whole page. Every field is replaced, including the ones left out. */
        ReplacePage: {
            /**
             * @description Markdown body, without frontmatter. Omitting this empties the page.
             * @example # Async in Rust
             *
             *     Futures are lazy. See [[notes/rust/pinning]].
             */
            content?: string;
            /**
             * @description Omitting this clears the page's tags. Use `PATCH` to leave them alone.
             * @example [
             *       "rust",
             *       "async"
             *     ]
             */
            tags?: string[];
            /**
             * @description Send `null` to let the title follow the body's first heading. Sending a
             *     title the server derived is what freezes it — see `title_derived`.
             * @example Async in Rust
             */
            title?: string | null;
        };
        RouteUsageView: {
            /**
             * Format: int64
             * @description Calls since the wiki was created. Counts survive restarts; they live in
             *     the durable half of the index, not the rebuildable half.
             * @example 412
             */
            count: number;
            /**
             * @description The HTTP method, uppercase.
             * @example GET
             */
            method: string;
            /**
             * @description The route template, as the OpenAPI document spells it.
             * @example /api/pages/{slug}
             */
            route: string;
        };
        SearchHitView: {
            /**
             * Format: double
             * @description Relevance. Higher is better; comparable only within one result set.
             * @example 1.87
             */
            score: number;
            slug: components["schemas"]["Slug"];
            /**
             * @description An excerpt of the body with matched terms wrapped in `<mark>`. This is
             *     here so a caller can judge which hits are worth fetching without
             *     pulling every body.
             *
             *     Only the marks are markup: the text around them is the page body
             *     verbatim and is **not** escaped, so a client rendering this as HTML
             *     would be rendering whatever the page contains.
             * @example Futures are <mark>lazy</mark>. See
             */
            snippet: string;
            /**
             * @description Its tags, so a caller can filter results without fetching each page.
             * @example [
             *       "rust",
             *       "async"
             *     ]
             */
            tags: string[];
            /**
             * @description The page's effective title.
             * @example Async in Rust
             */
            title: string;
        };
        SearchResponse: {
            /** @description Best first. */
            hits: components["schemas"]["SearchHitView"][];
            /**
             * @description The limit that was applied, after clamping.
             * @example 20
             */
            limit: number;
            /**
             * @description The offset that was applied.
             * @example 0
             */
            offset: number;
            /**
             * @description Total matches, not the number returned.
             * @example 3
             */
            total: number;
        };
        /**
         * @description A page's identifier: its path under the wiki root, `/`-separated, without the `.md` extension. `notes/rust/async.md` is `notes/rust/async`.
         *
         *     Slugs must not begin or end with `/`, contain an empty segment, `.`, `..`, a backslash, or any of `< > : " | ? *`. No segment may begin or end with a dot or whitespace, or be a reserved Windows device name such as `CON` or `LPT1` — a wiki written on one operating system stays valid on the other.
         *
         *     A rejected slug comes back as a `400` whose `details.rule` names which of these was broken.
         * @example notes/rust/async
         */
        Slug: string;
        StatsResponse: {
            /** @description API calls per route since the wiki was created, busiest first. */
            api_usage: components["schemas"]["RouteUsageView"][];
            /**
             * Format: date-time
             * @description When the index was last reconciled with the wiki directory.
             */
            last_indexed?: string | null;
            /** @description Link counts, split by where they point. */
            links: components["schemas"]["LinkTotalsView"];
            /** @description The most-linked-to pages, capped. */
            most_linked: components["schemas"]["LinkedPageView"][];
            /**
             * @description Pages nothing links to.
             * @example 1
             */
            orphan_count: number;
            /** @description A sample of them, capped. */
            orphans: components["schemas"]["PageRefView"][];
            /**
             * @description Pages in the index.
             * @example 6
             */
            pages: number;
            /** @description Every tag, most-used first. */
            tag_counts: components["schemas"]["TagCountView"][];
            /**
             * @description Distinct tags across every page.
             * @example 4
             */
            tags: number;
            /** @description The most-referenced of them, capped. */
            wanted: components["schemas"]["WantedPageView"][];
            /**
             * @description Distinct slugs that are linked to but do not exist.
             * @example 1
             */
            wanted_count: number;
        };
        TagCountView: {
            /**
             * @description How many pages carry this tag.
             * @example 4
             */
            pages: number;
            /**
             * @description The tag, exactly as pages spell it. Tags are not normalised.
             * @example rust
             */
            tag: string;
        };
        TagsResponse: {
            /** @description Most-used first. */
            tags: components["schemas"]["TagCountView"][];
        };
        WantedPageView: {
            /**
             * @description How many pages link to it — how badly it is wanted.
             * @example 2
             */
            referrers: number;
            /**
             * @description The slug that is linked to but does not exist.
             * @example notes/rust/streams
             */
            slug: string;
        };
    };
    responses: never;
    parameters: never;
    requestBodies: never;
    headers: never;
    pathItems: never;
}
export type $defs = Record<string, never>;
export interface operations {
    health: {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description The server is running */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["Health"];
                };
            };
        };
    };
    links: {
        parameters: {
            query?: never;
            header?: never;
            path: {
                /**
                 * @description Page slug
                 * @example notes/rust/async
                 */
                slug: string;
            };
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description Links into and out of the page */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["PageLinksResponse"];
                };
            };
            /** @description The slug is not valid */
            400: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["ErrorResponse"];
                };
            };
        };
    };
    move_page: {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        requestBody: {
            content: {
                "application/json": components["schemas"]["MovePage"];
            };
        };
        responses: {
            /** @description The page at its new slug */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["PageView"];
                };
            };
            /** @description One of the slugs is not valid */
            400: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["ErrorResponse"];
                };
            };
            /** @description No page at the source slug */
            404: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["ErrorResponse"];
                };
            };
            /** @description A page already exists at the destination */
            409: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["ErrorResponse"];
                };
            };
        };
    };
    list: {
        parameters: {
            query?: {
                /**
                 * @description Return only pages carrying this tag.
                 * @example rust
                 */
                tag?: string;
                /**
                 * @description Return only pages at or under this slug path.
                 *
                 *     `notes/rust` matches the page `notes/rust` and everything beneath it.
                 *     It stops at the separator, so `notes/rustlings` is a different
                 *     directory and does not match. Matching is case-sensitive.
                 * @example notes/rust
                 */
                prefix?: string;
                /**
                 * @description Return only pages sitting in a directory of this name, wherever in the
                 *     wiki that directory is.
                 *
                 *     `rust` matches `notes/rust/async` and `code/rust/traits` alike — the
                 *     flat reading of a slug, which is why it behaves like `tag` rather than
                 *     like `prefix`. A page's own name is not a directory it sits in, so
                 *     `async` does not match `notes/rust/async`.
                 * @example rust
                 */
                segment?: string;
                /**
                 * @description One of `slug`, `title`, `created`, `updated`. Defaults to `slug`.
                 * @example updated
                 */
                sort?: string;
                /**
                 * @description `asc` or `desc`. Defaults to `asc`.
                 * @example desc
                 */
                order?: string;
                /**
                 * @description Comma-separated subset of the summary fields to return, for cheap
                 *     listings. Naming an unknown field is refused, and the error lists the
                 *     ones that would have worked.
                 * @example slug,title,tags
                 */
                fields?: string;
                /**
                 * @description Defaults to 50, capped at 500.
                 * @example 50
                 */
                limit?: number;
                /**
                 * @description How many matches to skip. Pair it with `total` in the response.
                 * @example 0
                 */
                offset?: number;
            };
            header?: never;
            path?: never;
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description Matching pages */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["PageListResponse"];
                };
            };
            /** @description Unknown field, sort key, or order */
            400: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["ErrorResponse"];
                };
            };
        };
    };
    create: {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        requestBody: {
            content: {
                "application/json": components["schemas"]["CreatePage"];
            };
        };
        responses: {
            /** @description The page as written */
            201: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["PageView"];
                };
            };
            /** @description The slug is not valid */
            400: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["ErrorResponse"];
                };
            };
            /** @description A page already exists at that slug */
            409: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["ErrorResponse"];
                };
            };
        };
    };
    read: {
        parameters: {
            query?: {
                /**
                 * @description Also return the body rendered to HTML, in an `html` field. The markdown
                 *     is still returned either way.
                 * @example true
                 */
                render?: boolean;
            };
            header?: never;
            path: {
                /**
                 * @description Page slug, e.g. `notes/rust/async`
                 * @example notes/rust/async
                 */
                slug: string;
            };
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description The page */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["PageView"];
                };
            };
            /** @description The slug is not valid */
            400: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["ErrorResponse"];
                };
            };
            /** @description No page at that slug */
            404: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["ErrorResponse"];
                };
            };
            /** @description The page exists but could not be parsed */
            422: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["ErrorResponse"];
                };
            };
        };
    };
    replace: {
        parameters: {
            query?: never;
            header?: never;
            path: {
                /**
                 * @description Page slug
                 * @example notes/rust/async
                 */
                slug: string;
            };
            cookie?: never;
        };
        requestBody: {
            content: {
                "application/json": components["schemas"]["ReplacePage"];
            };
        };
        responses: {
            /** @description The page was replaced */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["PageView"];
                };
            };
            /** @description The page was created */
            201: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["PageView"];
                };
            };
            /** @description The slug is not valid */
            400: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["ErrorResponse"];
                };
            };
        };
    };
    delete: {
        parameters: {
            query?: never;
            header?: never;
            path: {
                /**
                 * @description Page slug
                 * @example notes/rust/async
                 */
                slug: string;
            };
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description The page was deleted */
            204: {
                headers: {
                    [name: string]: unknown;
                };
                content?: never;
            };
            /** @description The slug is not valid */
            400: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["ErrorResponse"];
                };
            };
            /** @description No page at that slug */
            404: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["ErrorResponse"];
                };
            };
        };
    };
    patch: {
        parameters: {
            query?: never;
            header?: never;
            path: {
                /**
                 * @description Page slug
                 * @example notes/rust/async
                 */
                slug: string;
            };
            cookie?: never;
        };
        requestBody: {
            content: {
                "application/json": components["schemas"]["PatchPage"];
            };
        };
        responses: {
            /** @description The page as updated */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["PageView"];
                };
            };
            /** @description The slug is not valid */
            400: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["ErrorResponse"];
                };
            };
            /** @description No page at that slug */
            404: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["ErrorResponse"];
                };
            };
        };
    };
    reindex: {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description What the rebuild found */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["ReindexResponse"];
                };
            };
        };
    };
    render_markdown: {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        requestBody: {
            content: {
                "application/json": components["schemas"]["RenderRequest"];
            };
        };
        responses: {
            /** @description The rendered HTML */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["RenderedHtml"];
                };
            };
            /** @description The request body is not valid */
            400: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["ErrorResponse"];
                };
            };
        };
    };
    search: {
        parameters: {
            query: {
                /**
                 * @description Terms to search for. Matched literally and combined with AND; a
                 *     trailing `*` on a term searches by prefix. Punctuation is safe to
                 *     include — it is never interpreted as query syntax.
                 * @example futures lazy*
                 */
                q: string;
                /**
                 * @description Defaults to 20, capped at 100.
                 * @example 20
                 */
                limit?: number;
                /**
                 * @description How many matches to skip. Pair it with `total` in the response.
                 * @example 0
                 */
                offset?: number;
            };
            header?: never;
            path?: never;
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description Matching pages, best first */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["SearchResponse"];
                };
            };
        };
    };
    stats: {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description Meta-stats for the whole wiki */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["StatsResponse"];
                };
            };
        };
    };
    tags: {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description All tags, most-used first */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["TagsResponse"];
                };
            };
        };
    };
}
