/**
 * This file was auto-generated by openapi-typescript.
 * Do not make direct changes to the file.
 */

export interface paths {
    "/api/health": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        /**
         * Report that the server is running, which wiki it is serving, and how fresh
         *     its index is.
         */
        get: operations["health"];
        put?: never;
        post?: never;
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/api/links/{slug}": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        /**
         * Both directions of a page's links.
         * @description The slug does not have to name a page that exists: asking about a wanted
         *     page returns what already points at it, which is what you want to see before
         *     deciding whether to write it.
         *
         *     Both directions come back together because that is how they are used — a
         *     page view shows its links and its backlinks at once, and one round trip
         *     beats two.
         */
        get: operations["links"];
        put?: never;
        post?: never;
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/api/move": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        get?: never;
        put?: never;
        /**
         * Move a page to a new slug.
         * @description Inbound links are left as they are. They become wanted pages, so a move
         *     shows up in the wiki's stats rather than rotting quietly.
         */
        post: operations["move_page"];
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/api/pages": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        /** List pages, without their bodies. */
        get: operations["list"];
        put?: never;
        /** Create a page. Fails if one already exists at that slug. */
        post: operations["create"];
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/api/pages/{slug}": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        /** Fetch a page, as markdown. */
        get: operations["read"];
        /** Create or wholly replace a page. */
        put: operations["replace"];
        post?: never;
        /** Delete a page. */
        delete: operations["delete"];
        options?: never;
        head?: never;
        /** Update some of a page, leaving the rest alone. */
        patch: operations["patch"];
        trace?: never;
    };
    "/api/reindex": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        get?: never;
        put?: never;
        /**
         * Rebuild the search index from the wiki directory.
         * @description The index holds nothing that is not already on disk, so this is always safe
         *     and never loses anything. It is the escape hatch for the one case
         *     incremental scanning can miss: an edit that leaves both mtime and size
         *     unchanged.
         */
        post: operations["reindex"];
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/api/search": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        /** Search page titles and bodies. */
        get: operations["search"];
        put?: never;
        post?: never;
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/api/stats": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        /**
         * The wiki's meta-stats.
         * @description Orphans and wanted pages are the two most useful numbers here, and they are
         *     two sides of the same thing: pages nothing reaches, and reaches with nothing
         *     at the end. A wiki that branches chaotically accumulates both.
         */
        get: operations["stats"];
        put?: never;
        post?: never;
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/api/tags": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        /** Every tag in the wiki, with page counts. */
        get: operations["tags"];
        put?: never;
        post?: never;
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
}
export type webhooks = Record<string, never>;
export interface components {
    schemas: {
        CreatePage: {
            /** @description Markdown body, without frontmatter. */
            content?: string;
            slug: components["schemas"]["Slug"];
            tags?: string[];
            /**
             * @description Optional. Without it the title falls back to the body's first heading,
             *     then to the slug.
             */
            title?: string | null;
        };
        ErrorDetail: {
            /**
             * @description Stable, machine-readable identifier for what went wrong.
             * @example page_not_found
             */
            code: string;
            /** @description Context for correcting the request, when there is any. */
            details?: unknown;
            /**
             * @description Human-readable explanation. Prose; do not branch on it.
             * @example no page at notes/asnyc
             */
            message: string;
        };
        ErrorResponse: {
            error: components["schemas"]["ErrorDetail"];
        };
        Health: {
            /**
             * Format: date-time
             * @description When the index was last reconciled with the wiki directory. Null if it
             *     has not been scanned yet.
             */
            last_indexed?: string | null;
            /**
             * @description Number of pages currently indexed.
             * @example 42
             */
            pages: number;
            /**
             * @description Always `"ok"` — a response at all is the liveness signal.
             * @example ok
             */
            status: string;
            /**
             * @description The running Rhizowiki version.
             * @example 0.1.0
             */
            version: string;
            /** @description Absolute path of the wiki directory being served. */
            wiki_root: string;
        };
        InboundLinkView: {
            display?: string | null;
            kind: string;
            /** @description The page that links here. */
            slug: components["schemas"]["Slug"];
            title: string;
        };
        LinkTotalsView: {
            external: number;
            /** @description Links pointing at pages, whether or not those pages exist. */
            internal: number;
            /** @description Internal links whose target exists. */
            resolved: number;
            /** @description Internal links whose target has not been written yet. */
            wanted: number;
        };
        LinkedPageView: {
            referrers: number;
            slug: components["schemas"]["Slug"];
            title: string;
        };
        MovePage: {
            from: components["schemas"]["Slug"];
            to: components["schemas"]["Slug"];
        };
        OutboundLinkView: {
            /** @description The link's text, when it says something other than the target. */
            display?: string | null;
            /**
             * @description `wiki` (`[[slug]]`), `internal` (a markdown link to a page), or
             *     `external`.
             * @example wiki
             */
            kind: string;
            /**
             * @description Whether this points at a page that exists. A `false` here is not an
             *     error — it is a wanted page.
             */
            resolved: boolean;
            /** @description A slug for `wiki` and `internal` links, a URL for `external` ones. */
            target: string;
            /** @description Title of the target page, when it exists. */
            title?: string | null;
        };
        PageLinksResponse: {
            /** @description Whether the page itself exists. Links can point at pages that do not. */
            exists: boolean;
            inbound: components["schemas"]["InboundLinkView"][];
            outbound: components["schemas"]["OutboundLinkView"][];
            slug: components["schemas"]["Slug"];
        };
        PageListResponse: {
            limit: number;
            offset: number;
            /**
             * @description Bodies are never included here. When `fields` is given, each entry
             *     carries only the requested subset of these keys.
             */
            pages: components["schemas"]["PageSummary"][];
            /** @description Total matching pages, not the number returned. */
            total: number;
        };
        PageRefView: {
            slug: components["schemas"]["Slug"];
            title: string;
        };
        /** @description A page without its content. */
        PageSummary: {
            /** Format: date-time */
            created: string;
            /** Format: int64 */
            size: number;
            slug: components["schemas"]["Slug"];
            tags: string[];
            title: string;
            /** Format: date-time */
            updated: string;
        };
        /** @description A page and its content. */
        PageView: {
            /**
             * @description The page body as markdown, without its frontmatter. Title and tags are
             *     returned as fields above rather than left in the text, so an editor
             *     never has to reserialise YAML to change one of them.
             */
            content: string;
            /** Format: date-time */
            created: string;
            /**
             * @description The body rendered to HTML. Present only when `render=true` was asked
             *     for. Raw HTML in the source is escaped, never passed through.
             */
            html?: string | null;
            /**
             * Format: int64
             * @description Size of the page's file on disk, in bytes.
             */
            size: number;
            slug: components["schemas"]["Slug"];
            tags: string[];
            /** @example Rhizome */
            title: string;
            /** Format: date-time */
            updated: string;
        };
        /** @description A partial update. Omitted fields are left alone. */
        PatchPage: {
            content?: string | null;
            tags?: string[] | null;
            /**
             * @description Omit to leave the title unchanged; send `null` to clear it and fall
             *     back to the heading or slug.
             */
            title?: string | null;
        };
        ReindexResponse: {
            /** @description Pages on disk that could not be read, and so are not searchable. */
            failed: number;
            /** @description Pages read and written to the index. */
            indexed: number;
            /** @description Pages dropped because they are no longer on disk. */
            removed: number;
            /** @description Pages found on disk. */
            scanned: number;
        };
        ReplacePage: {
            content?: string;
            tags?: string[];
            title?: string | null;
        };
        RouteUsageView: {
            /** Format: int64 */
            count: number;
            method: string;
            /**
             * @description The route template, as the OpenAPI document spells it.
             * @example /api/pages/{slug}
             */
            route: string;
        };
        SearchHitView: {
            /**
             * Format: double
             * @description Relevance. Higher is better; comparable only within one result set.
             */
            score: number;
            slug: components["schemas"]["Slug"];
            /**
             * @description An excerpt of the body with matched terms wrapped in `<mark>`. This is
             *     here so a caller can judge which hits are worth fetching without
             *     pulling every body.
             * @example knowledge branches off <mark>chaotically</mark>
             */
            snippet: string;
            tags: string[];
            title: string;
        };
        SearchResponse: {
            hits: components["schemas"]["SearchHitView"][];
            limit: number;
            offset: number;
            /** @description Total matches, not the number returned. */
            total: number;
        };
        /**
         * @description A validated page identifier.
         *
         *     The only way to construct one is [`Slug::parse`], so holding a `Slug` is
         *     proof that the invariants below hold.
         * @example notes/rust/async
         */
        Slug: string;
        StatsResponse: {
            /** @description API calls per route since the wiki was created, busiest first. */
            api_usage: components["schemas"]["RouteUsageView"][];
            /**
             * Format: date-time
             * @description When the index was last reconciled with the wiki directory.
             */
            last_indexed?: string | null;
            links: components["schemas"]["LinkTotalsView"];
            /** @description The most-linked-to pages, capped. */
            most_linked: components["schemas"]["LinkedPageView"][];
            /** @description Pages nothing links to. */
            orphan_count: number;
            /** @description A sample of them, capped. */
            orphans: components["schemas"]["PageRefView"][];
            pages: number;
            /** @description Every tag, most-used first. */
            tag_counts: components["schemas"]["TagCountView"][];
            tags: number;
            /** @description The most-referenced of them, capped. */
            wanted: components["schemas"]["WantedPageView"][];
            /** @description Distinct slugs that are linked to but do not exist. */
            wanted_count: number;
        };
        TagCountView: {
            /** @description How many pages carry this tag. */
            pages: number;
            tag: string;
        };
        TagsResponse: {
            /** @description Most-used first. */
            tags: components["schemas"]["TagCountView"][];
        };
        WantedPageView: {
            referrers: number;
            /** @description The slug that is linked to but does not exist. */
            slug: string;
        };
    };
    responses: never;
    parameters: never;
    requestBodies: never;
    headers: never;
    pathItems: never;
}
export type $defs = Record<string, never>;
export interface operations {
    health: {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description The server is running */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["Health"];
                };
            };
        };
    };
    links: {
        parameters: {
            query?: never;
            header?: never;
            path: {
                /**
                 * @description Page slug
                 * @example notes/rust/async
                 */
                slug: string;
            };
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description Links into and out of the page */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["PageLinksResponse"];
                };
            };
            /** @description The slug is not valid */
            400: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["ErrorResponse"];
                };
            };
        };
    };
    move_page: {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        requestBody: {
            content: {
                "application/json": components["schemas"]["MovePage"];
            };
        };
        responses: {
            /** @description The page at its new slug */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["PageView"];
                };
            };
            /** @description One of the slugs is not valid */
            400: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["ErrorResponse"];
                };
            };
            /** @description No page at the source slug */
            404: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["ErrorResponse"];
                };
            };
            /** @description A page already exists at the destination */
            409: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["ErrorResponse"];
                };
            };
        };
    };
    list: {
        parameters: {
            query?: {
                /** @description Return only pages carrying this tag. */
                tag?: string;
                /** @description One of `slug`, `title`, `created`, `updated`. Defaults to `slug`. */
                sort?: string;
                /** @description `asc` or `desc`. Defaults to `asc`. */
                order?: string;
                /**
                 * @description Comma-separated subset of the summary fields to return, for cheap
                 *     listings — for example `slug,title,tags`.
                 */
                fields?: string;
                /** @description Defaults to 50, capped at 500. */
                limit?: number;
                offset?: number;
            };
            header?: never;
            path?: never;
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description Matching pages */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["PageListResponse"];
                };
            };
            /** @description Unknown field, sort key, or order */
            400: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["ErrorResponse"];
                };
            };
        };
    };
    create: {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        requestBody: {
            content: {
                "application/json": components["schemas"]["CreatePage"];
            };
        };
        responses: {
            /** @description The page as written */
            201: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["PageView"];
                };
            };
            /** @description The slug is not valid */
            400: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["ErrorResponse"];
                };
            };
            /** @description A page already exists at that slug */
            409: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["ErrorResponse"];
                };
            };
        };
    };
    read: {
        parameters: {
            query?: {
                /** @description Also return the body rendered to HTML, in an `html` field. */
                render?: boolean;
            };
            header?: never;
            path: {
                /**
                 * @description Page slug, e.g. `notes/rust/async`
                 * @example notes/rust/async
                 */
                slug: string;
            };
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description The page */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["PageView"];
                };
            };
            /** @description The slug is not valid */
            400: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["ErrorResponse"];
                };
            };
            /** @description No page at that slug */
            404: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["ErrorResponse"];
                };
            };
            /** @description The page exists but could not be parsed */
            422: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["ErrorResponse"];
                };
            };
        };
    };
    replace: {
        parameters: {
            query?: never;
            header?: never;
            path: {
                /**
                 * @description Page slug
                 * @example notes/rust/async
                 */
                slug: string;
            };
            cookie?: never;
        };
        requestBody: {
            content: {
                "application/json": components["schemas"]["ReplacePage"];
            };
        };
        responses: {
            /** @description The page was replaced */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["PageView"];
                };
            };
            /** @description The page was created */
            201: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["PageView"];
                };
            };
            /** @description The slug is not valid */
            400: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["ErrorResponse"];
                };
            };
        };
    };
    delete: {
        parameters: {
            query?: never;
            header?: never;
            path: {
                /**
                 * @description Page slug
                 * @example notes/rust/async
                 */
                slug: string;
            };
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description The page was deleted */
            204: {
                headers: {
                    [name: string]: unknown;
                };
                content?: never;
            };
            /** @description The slug is not valid */
            400: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["ErrorResponse"];
                };
            };
            /** @description No page at that slug */
            404: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["ErrorResponse"];
                };
            };
        };
    };
    patch: {
        parameters: {
            query?: never;
            header?: never;
            path: {
                /**
                 * @description Page slug
                 * @example notes/rust/async
                 */
                slug: string;
            };
            cookie?: never;
        };
        requestBody: {
            content: {
                "application/json": components["schemas"]["PatchPage"];
            };
        };
        responses: {
            /** @description The page as updated */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["PageView"];
                };
            };
            /** @description The slug is not valid */
            400: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["ErrorResponse"];
                };
            };
            /** @description No page at that slug */
            404: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["ErrorResponse"];
                };
            };
        };
    };
    reindex: {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description What the rebuild found */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["ReindexResponse"];
                };
            };
        };
    };
    search: {
        parameters: {
            query: {
                /**
                 * @description Terms to search for. Matched literally and combined with AND; a
                 *     trailing `*` on a term searches by prefix. Punctuation is safe to
                 *     include — it is never interpreted as query syntax.
                 * @example rhizome branch*
                 */
                q: string;
                /** @description Defaults to 20, capped at 100. */
                limit?: number;
                offset?: number;
            };
            header?: never;
            path?: never;
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description Matching pages, best first */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["SearchResponse"];
                };
            };
        };
    };
    stats: {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description Meta-stats for the whole wiki */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["StatsResponse"];
                };
            };
        };
    };
    tags: {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description All tags, most-used first */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["TagsResponse"];
                };
            };
        };
    };
}
