//! Time entries: what one is, how it is named, and how it sits in a file.
//!
//! A time entry records that something took from one instant to another. It has
//! a **name**, which is the only grouping there is — every entry called
//! `Deep work` is the same activity — and it may carry a markdown **note**, so
//! an entry can say what actually happened rather than just how long it took.
//!
//! ```markdown
//! ---
//! name: Deep work
//! start: 2026-08-06T14:25:30Z
//! end: 2026-08-06T15:40:00Z
//! pages:
//!   - notes/rust/async
//! ---
//!
//! Chased down a lifetime error in the poll loop.
//! ```
//!
//! An entry with no `end` is **running**. Several may run at once and they are
//! allowed to overlap: a timer is a record of attention, and attention is not
//! exclusive. Nothing here enforces otherwise.
//!
//! `pages` is the link to the rest of the wiki, and it is deliberately the only
//! one — see [`crate::index::times`] for why a time link is not an ordinary
//! link.

pub mod stats;
pub mod store;

use std::fmt;
use std::path::{Path, PathBuf};

use chrono::{DateTime, NaiveDateTime, Utc};
use serde::{Deserialize, Deserializer, Serialize, Serializer, de::Error as _};
use thiserror::Error;
use utoipa::ToSchema;

use crate::frontmatter::{self, FrontmatterError};
use crate::slug::Slug;

pub use store::{TimeDraft, TimeStore, TimeStoreError, TimeWalkEntry};

/// Where time entries live inside the wiki, under [`crate::store::INTERNAL_DIR`].
///
/// Under the dot-directory rather than beside the pages, because the page
/// walker, the slug validator and the file watcher all already agree that
/// nothing there is a page. Putting times in a visible `times/` directory would
/// mean teaching all three about a name the user might legitimately want for
/// their own pages; this way a time entry cannot be mistaken for one, and a
/// page cannot be written over one.
///
/// It is not derived data, though it shares a directory with the index that is.
/// `.rhizolog/index.db` can be deleted at any time; `.rhizolog/times/` is the
/// only copy of the time log.
pub const TIMES_DIR: &str = "times";

/// The number of characters in a [`TimeId`]: `20260806T142530-123456789`.
const ID_LEN: usize = 25;

/// How the timestamp half of an id is spelled.
const ID_STAMP_FORMAT: &str = "%Y%m%dT%H%M%S";

#[derive(Debug, Clone, PartialEq, Eq, Error)]
pub enum TimeIdError {
    #[error("a time id is {ID_LEN} characters like `20260806T142530-123456789`, not {length}")]
    Length { length: usize },

    #[error("a time id may only contain digits, one `T` and one `-`")]
    Shape,

    #[error("`{stamp}` is not a real date and time")]
    Timestamp { stamp: String },
}

/// A time entry's identifier, and its filename.
///
/// The format is `<UTC start, compacted>-<nanoseconds>`:
/// `20260806T142530-123456789`. Two properties are load-bearing.
///
/// It **sorts chronologically as text**, so the directory listing is the log in
/// order and so is any `order by id`.
///
/// And it is **rigid**, which is the whole reason it is a newtype. An id
/// arrives from HTTP and becomes a filesystem path, exactly as a [`Slug`] does.
/// A slug has to accommodate whatever a person wants to call a page, so its
/// validation is a list of hazards to exclude; an id is generated, never typed,
/// so it can be validated by exact shape instead. Twenty-five characters drawn
/// from digits, one `T` and one `-` cannot express a traversal, a drive prefix,
/// a device name or a dot-segment, so there is nothing to enumerate.
#[derive(Debug, Clone, PartialEq, Eq, PartialOrd, Ord, Hash, ToSchema)]
#[schema(
    value_type = String,
    example = "20260806T142530-123456789",
    description = "A time entry's identifier: the UTC instant it was first recorded for, \
                   compacted, plus nanoseconds. `20260806T142530-123456789`.\n\n\
                   Ids are generated by the server, never chosen by a caller, and they \
                   sort chronologically as plain text."
)]
pub struct TimeId(String);

impl TimeId {
    pub fn parse(raw: &str) -> Result<Self, TimeIdError> {
        // Counting characters rather than bytes so a multi-byte character
        // reports the shape error below instead of a confusing length.
        let length = raw.chars().count();
        if length != ID_LEN {
            return Err(TimeIdError::Length { length });
        }

        let bytes = raw.as_bytes();
        let shaped = bytes.iter().enumerate().all(|(at, byte)| match at {
            8 => *byte == b'T',
            15 => *byte == b'-',
            _ => byte.is_ascii_digit(),
        });
        if !shaped {
            return Err(TimeIdError::Shape);
        }

        // The shape allows `20261340T996060`. Parsing is what rejects it, and
        // it matters: the month in the id decides which directory the file
        // lives in.
        let stamp = &raw[..15];
        if NaiveDateTime::parse_from_str(stamp, ID_STAMP_FORMAT).is_err() {
            return Err(TimeIdError::Timestamp {
                stamp: stamp.to_owned(),
            });
        }

        Ok(Self(raw.to_owned()))
    }

    /// Mint an id for an entry starting at `start`.
    ///
    /// `nudge` shifts the nanosecond half, and exists because a manually
    /// entered start almost never has sub-second precision: two entries logged
    /// for `09:00:00` would otherwise mint the same id and the second would
    /// overwrite the first. [`TimeStore::create`](store::TimeStore::create)
    /// walks `nudge` upward until it finds a free file.
    pub fn mint(start: DateTime<Utc>, nudge: u32) -> Self {
        let nanos = (u64::from(start.timestamp_subsec_nanos()) + u64::from(nudge)) % 1_000_000_000;
        Self(format!("{}-{nanos:09}", start.format(ID_STAMP_FORMAT)))
    }

    pub fn as_str(&self) -> &str {
        &self.0
    }

    /// The `YYYY-MM` directory this entry's file belongs in.
    ///
    /// Taken from the id rather than from the entry's `start`, so the path is a
    /// pure function of the id: editing an entry's start time never moves its
    /// file, and nothing has to keep two spellings of "which month" in step.
    pub fn month(&self) -> String {
        format!("{}-{}", &self.0[..4], &self.0[4..6])
    }

    /// Build the on-disk path for this entry under the times directory.
    pub fn to_path(&self, root: &Path) -> PathBuf {
        root.join(self.month()).join(format!("{}.md", self.0))
    }

    /// Recover an id from a path relative to the times directory.
    ///
    /// Returns `None` for anything that is not a file this module would have
    /// written, so the walker skips strays rather than indexing entries it
    /// could never serve.
    pub fn from_relative_path(path: &Path) -> Option<Self> {
        let mut segments = Vec::new();
        for component in path.components() {
            match component {
                std::path::Component::Normal(part) => segments.push(part.to_str()?),
                _ => return None,
            }
        }

        let [month, file_name] = segments.as_slice() else {
            return None;
        };
        let stem = file_name.strip_suffix(".md")?;
        let id = Self::parse(stem).ok()?;

        // A file filed under the wrong month would be found by the walker and
        // then written back somewhere else, so it is not one of ours.
        (id.month() == *month).then_some(id)
    }
}

impl fmt::Display for TimeId {
    fn fmt(&self, f: &mut fmt::Formatter<'_>) -> fmt::Result {
        f.write_str(&self.0)
    }
}

impl AsRef<str> for TimeId {
    fn as_ref(&self) -> &str {
        &self.0
    }
}

impl From<TimeId> for String {
    fn from(id: TimeId) -> Self {
        id.0
    }
}

impl Serialize for TimeId {
    fn serialize<S: Serializer>(&self, serializer: S) -> Result<S::Ok, S::Error> {
        serializer.serialize_str(&self.0)
    }
}

impl<'de> Deserialize<'de> for TimeId {
    fn deserialize<D: Deserializer<'de>>(deserializer: D) -> Result<Self, D::Error> {
        let raw = String::deserialize(deserializer)?;
        Self::parse(&raw).map_err(D::Error::custom)
    }
}

/// A time entry's frontmatter, exactly as it appears in the file.
///
/// `name` and `start` are `Option` here and not on [`TimeEntry`]: the struct
/// describes what a file might contain, and a file might be missing them. The
/// parse below is where that becomes an error.
#[derive(Debug, Clone, Default, PartialEq, Eq, Serialize, Deserialize)]
pub struct TimeFrontmatter {
    #[serde(default, skip_serializing_if = "Option::is_none")]
    pub name: Option<String>,

    #[serde(default, skip_serializing_if = "Option::is_none")]
    pub start: Option<DateTime<Utc>>,

    /// Absent while the timer is running.
    #[serde(default, skip_serializing_if = "Option::is_none")]
    pub end: Option<DateTime<Utc>>,

    /// The pages this time was spent on.
    #[serde(default, skip_serializing_if = "Vec::is_empty")]
    pub pages: Vec<Slug>,
}

#[derive(Debug, Error)]
pub enum TimeError {
    #[error(transparent)]
    Frontmatter(#[from] FrontmatterError),

    #[error("a time entry needs a `{field}` in its frontmatter")]
    MissingField { field: &'static str },
}

/// One recorded stretch of time, as parsed from a file on disk.
#[derive(Debug, Clone, PartialEq, Eq)]
pub struct TimeEntry {
    pub id: TimeId,
    /// The activity. Entries are grouped by this, spelled exactly as written.
    pub name: String,
    pub start: DateTime<Utc>,
    /// `None` while the timer is running.
    pub end: Option<DateTime<Utc>>,
    /// The pages this time is attached to, deduplicated, in file order.
    pub pages: Vec<Slug>,
    /// A markdown note, without the frontmatter. Usually empty.
    pub note: String,
    /// The file's mtime. Not part of the file's contents.
    pub updated: DateTime<Utc>,
    /// The file's length in bytes, as it sits on disk — see [`crate::page::Page::size`]
    /// for why this must not be measured from anything re-serialised.
    pub size: u64,
}

impl TimeEntry {
    pub fn from_markdown(
        id: TimeId,
        text: &str,
        updated: DateTime<Utc>,
    ) -> Result<Self, TimeError> {
        let size = text.len() as u64;
        let text = frontmatter::strip_bom(text);

        let (fields, note): (TimeFrontmatter, &str) = match frontmatter::split(text)? {
            Some((yaml, body)) => (frontmatter::parse(yaml)?, body),
            None => (TimeFrontmatter::default(), text),
        };

        // A note can be invented and a page list can be empty, but nothing can
        // stand in for when the time was spent, and a missing name would
        // conjure a group that the author never named.
        let name = fields
            .name
            .ok_or(TimeError::MissingField { field: "name" })?;
        let start = fields
            .start
            .ok_or(TimeError::MissingField { field: "start" })?;

        Ok(Self {
            id,
            name,
            start,
            end: fields.end,
            pages: dedupe(fields.pages),
            note: note.to_owned(),
            updated,
            size,
        })
    }

    pub fn to_markdown(&self) -> String {
        let yaml = serde_yaml_ng::to_string(&TimeFrontmatter {
            name: Some(self.name.clone()),
            start: Some(self.start),
            end: self.end,
            pages: self.pages.clone(),
        })
        .expect("time frontmatter is a plain struct of strings and timestamps");

        frontmatter::compose(&yaml, &self.note)
    }

    pub fn is_running(&self) -> bool {
        self.end.is_none()
    }

    /// When this entry stops counting: its end, or `now` while it runs.
    pub fn effective_end(&self, now: DateTime<Utc>) -> DateTime<Utc> {
        self.end.unwrap_or(now)
    }

    /// How long the entry lasted, in whole seconds.
    ///
    /// Clamped at zero. An `end` before its `start` is refused when it arrives
    /// through the API, but a file edited by hand can say anything, and a
    /// negative duration poisoning every total is a worse answer than a zero.
    pub fn seconds(&self, now: DateTime<Utc>) -> u64 {
        (self.effective_end(now) - self.start)
            .num_seconds()
            .max(0)
            .unsigned_abs()
    }

    pub fn has_note(&self) -> bool {
        !self.note.trim().is_empty()
    }
}

/// Keep the first mention of each page and drop the rest.
fn dedupe(pages: Vec<Slug>) -> Vec<Slug> {
    let mut seen = std::collections::HashSet::new();
    pages
        .into_iter()
        .filter(|page| seen.insert(page.clone()))
        .collect()
}

#[cfg(test)]
mod tests {
    use super::*;

    fn at(text: &str) -> DateTime<Utc> {
        DateTime::parse_from_rfc3339(text)
            .expect("valid timestamp")
            .with_timezone(&Utc)
    }

    fn id(raw: &str) -> TimeId {
        TimeId::parse(raw).expect("valid time id")
    }

    #[test]
    fn ids_are_minted_from_the_start_instant() {
        let minted = TimeId::mint(at("2026-08-06T14:25:30.123456789Z"), 0);
        assert_eq!(minted.as_str(), "20260806T142530-123456789");
        assert_eq!(minted.month(), "2026-08");
    }

    /// A manually entered start is whole seconds, so two of them on the same
    /// second must not mint the same id.
    #[test]
    fn the_nudge_separates_two_entries_at_the_same_instant() {
        let start = at("2026-08-06T09:00:00Z");
        assert_eq!(TimeId::mint(start, 0).as_str(), "20260806T090000-000000000");
        assert_eq!(TimeId::mint(start, 1).as_str(), "20260806T090000-000000001");
        assert_ne!(TimeId::mint(start, 0), TimeId::mint(start, 1));
    }

    /// The property the whole log leans on for ordering.
    #[test]
    fn ids_sort_chronologically_as_text() {
        let mut ids = [
            TimeId::mint(at("2026-08-06T14:25:30Z"), 0),
            TimeId::mint(at("2025-01-01T00:00:00Z"), 0),
            TimeId::mint(at("2026-08-06T14:25:31Z"), 0),
        ];
        ids.sort();
        assert_eq!(
            ids.map(|id| id.as_str().to_owned()),
            [
                "20250101T000000-000000000",
                "20260806T142530-000000000",
                "20260806T142531-000000000",
            ]
        );
    }

    /// An id becomes a filesystem path, so the shape is the whole defence.
    #[test]
    fn rejects_anything_that_is_not_exactly_an_id() {
        for raw in [
            "",
            "20260806T142530",
            "20260806T142530-12345678",
            "20260806T142530-1234567890",
            "../../../../../../etc/passwd",
            "20260806X142530-123456789",
            "20260806T142530_123456789",
            "2026080aT142530-123456789",
            "20260806T142530-12345678a",
            "20260806T142530-12345678\u{e9}",
        ] {
            assert!(TimeId::parse(raw).is_err(), "{raw:?} was accepted");
        }

        // Shaped correctly but not a real instant.
        assert!(matches!(
            TimeId::parse("20261340T142530-123456789"),
            Err(TimeIdError::Timestamp { .. })
        ));
        assert!(matches!(
            TimeId::parse("20260806T256130-123456789"),
            Err(TimeIdError::Timestamp { .. })
        ));
    }

    #[test]
    fn paths_are_grouped_by_the_month_in_the_id() {
        let path = id("20260806T142530-123456789").to_path(Path::new("/wiki/.rhizolog/times"));
        assert_eq!(
            path,
            Path::new("/wiki/.rhizolog/times/2026-08/20260806T142530-123456789.md")
        );
    }

    #[test]
    fn round_trips_through_a_relative_path() {
        let original = id("20260806T142530-123456789");
        let path = original.to_path(Path::new(""));
        assert_eq!(TimeId::from_relative_path(&path), Some(original));
    }

    #[test]
    fn ignores_paths_that_are_not_entries() {
        for path in [
            "2026-08/notes.md",
            "20260806T142530-123456789.md",
            "2026-08/20260806T142530-123456789.txt",
            "2026-08/sub/20260806T142530-123456789.md",
            // Filed under a month it does not belong to.
            "2026-07/20260806T142530-123456789.md",
        ] {
            assert_eq!(TimeId::from_relative_path(Path::new(path)), None, "{path}");
        }
    }

    fn entry(text: &str) -> TimeEntry {
        TimeEntry::from_markdown(
            id("20260806T142530-123456789"),
            text,
            at("2026-08-06T16:00:00Z"),
        )
        .expect("entry should parse")
    }

    #[test]
    fn parses_a_finished_entry() {
        let parsed = entry(
            "---\nname: Deep work\nstart: 2026-08-06T14:25:30Z\nend: 2026-08-06T15:40:00Z\npages:\n- notes/rust/async\n---\n\nChased a lifetime error.\n",
        );

        assert_eq!(parsed.name, "Deep work");
        assert_eq!(parsed.start, at("2026-08-06T14:25:30Z"));
        assert_eq!(parsed.end, Some(at("2026-08-06T15:40:00Z")));
        assert_eq!(parsed.pages[0].as_str(), "notes/rust/async");
        assert_eq!(parsed.note, "\nChased a lifetime error.\n");
        assert!(!parsed.is_running());
        assert_eq!(parsed.seconds(at("2026-08-06T20:00:00Z")), 74 * 60 + 30);
        assert!(parsed.has_note());
    }

    #[test]
    fn an_entry_with_no_end_is_still_running_and_counts_up() {
        let parsed = entry("---\nname: Deep work\nstart: 2026-08-06T14:25:30Z\n---\n");

        assert!(parsed.is_running());
        assert_eq!(parsed.seconds(at("2026-08-06T14:26:30Z")), 60);
        assert!(!parsed.has_note());
    }

    /// A hand-edited file can say anything, and a negative duration would
    /// poison every total it appears in.
    #[test]
    fn an_end_before_its_start_counts_as_nothing() {
        let parsed = entry(
            "---\nname: Backwards\nstart: 2026-08-06T14:00:00Z\nend: 2026-08-06T13:00:00Z\n---\n",
        );
        assert_eq!(parsed.seconds(at("2026-08-06T20:00:00Z")), 0);
    }

    #[test]
    fn a_file_missing_what_cannot_be_invented_is_refused() {
        for text in [
            "---\nstart: 2026-08-06T14:25:30Z\n---\n",
            "---\nname: Deep work\n---\n",
            "Just a note, no frontmatter.\n",
        ] {
            let result = TimeEntry::from_markdown(
                id("20260806T142530-123456789"),
                text,
                at("2026-08-06T16:00:00Z"),
            );
            assert!(
                matches!(result, Err(TimeError::MissingField { .. })),
                "{text:?}"
            );
        }
    }

    #[test]
    fn round_trips_unchanged() {
        let text = "---\nname: Deep work\nstart: 2026-08-06T14:25:30Z\nend: 2026-08-06T15:40:00Z\npages:\n- notes/rust/async\n---\n\nChased a lifetime error.\n";
        assert_eq!(entry(text).to_markdown(), text);
    }

    /// Same trap as a page: the BOM is invisible and takes the whole
    /// frontmatter block with it.
    #[test]
    fn a_utf8_bom_does_not_hide_the_frontmatter() {
        let parsed = entry("\u{feff}---\nname: Deep work\nstart: 2026-08-06T14:25:30Z\n---\n");
        assert_eq!(parsed.name, "Deep work");
    }

    #[test]
    fn a_repeated_page_is_recorded_once() {
        let parsed = entry(
            "---\nname: Deep work\nstart: 2026-08-06T14:25:30Z\npages:\n- notes/a\n- notes/a\n- notes/b\n---\n",
        );
        let pages: Vec<&str> = parsed.pages.iter().map(Slug::as_str).collect();
        assert_eq!(pages, ["notes/a", "notes/b"]);
    }
}
