//! The window that changes what the app remembers.
//!
//! Configuration that belongs to *this copy of the app* rather than to the wiki
//! — which port to serve on, so far — has to be changeable without a text
//! editor. There is nowhere in the dashboard it could live: that page is the
//! one a browser loads from a remote instance, and a control that only worked
//! when it happened to be inside Tauri would make the two different
//! applications. See `knowledge-base/desktop-app.md`.
//!
//! So it is a second window, owned by the shell, which never loads the
//! dashboard and never talks to the API.
//!
//! ## Its own scheme, which is the point
//!
//! The dashboard cannot reach Tauri's JavaScript because its origin is
//! `http://127.0.0.1:<port>`, which Tauri treats as remote — a capability would
//! have to name that URL, and the port is the one thing that varies. This
//! window is served over `rhizolog-settings://` by [`respond`] below, so its
//! origin is fixed and belongs to the shell. The thing that made a settings
//! page impossible in the dashboard is exactly the thing this does not have.
//!
//! ## No JavaScript, and no IPC either
//!
//! Having a scheme of its own would allow IPC, and it is still not worth
//! having. The page is an HTML form that posts back to the same scheme, and
//! this module answers the post — which is the entire interaction, with nothing
//! to keep in step between two languages and no capability file to get wrong.

use std::borrow::Cow;
use std::net::SocketAddr;

use rhizolog::Server;
use tauri::http::{Request, Response, StatusCode, header};
use tauri::{AppHandle, Manager, Url, WebviewUrl, WebviewWindowBuilder};

use crate::settings;

/// The scheme this window is served over.
///
/// Registered on the `tauri::Builder`, which is what makes it reach [`respond`]
/// rather than the network.
pub const SCHEME: &str = "rhizolog-settings";

/// The window's label.
///
/// Also the permission check in [`respond`]: it is the only webview whose
/// requests are answered. Nothing generated by [`crate::label_for`] can collide
/// with it, which the tests below hold to.
pub const LABEL: &str = "settings";

/// Show the settings, or raise the window already showing them.
pub fn open(handle: &AppHandle) -> tauri::Result<()> {
    if let Some(already) = handle.get_webview_window(LABEL) {
        let _ = already.unminimize();
        let _ = already.set_focus();
        return Ok(());
    }

    // No menu: the File menu restarts the application, which is not a thing to
    // offer from the window that is about to do that on purpose.
    WebviewWindowBuilder::new(handle, LABEL, WebviewUrl::CustomProtocol(url()))
        .title("Rhizolog Settings")
        .inner_size(560.0, 480.0)
        .min_inner_size(420.0, 380.0)
        .build()?;

    Ok(())
}

/// Where the window points.
///
/// Tauri serves a custom scheme at `http://<scheme>.localhost` on Windows,
/// because WebView2 has no way to add a real one to an existing environment,
/// and at `<scheme>://localhost` everywhere else.
fn url() -> Url {
    let text = if cfg!(any(windows, target_os = "android")) {
        format!("http://{SCHEME}.localhost/")
    } else {
        format!("{SCHEME}://localhost/")
    };

    Url::parse(&text).expect("the settings url is a constant")
}

/// Answer a request on the settings scheme.
///
/// `webview` is the label of the window that asked.
pub fn respond(
    handle: &AppHandle,
    webview: &str,
    request: &Request<Vec<u8>>,
) -> Response<Cow<'static, [u8]>> {
    // Every webview in the process can see a registered scheme, the dashboard's
    // included — and the dashboard renders whatever the wiki says. A page that
    // posted this form would be a note in a wiki changing which port the app
    // serves on, so the shell's own window is the only one answered.
    if webview != LABEL {
        tracing::warn!(webview, "refused a settings request from another window");
        return plain(StatusCode::FORBIDDEN, "Not for this window.");
    }

    match (request.method().as_str(), request.uri().path()) {
        ("GET", "/") => {
            // A window with nothing in it is the failure mode here, and the log
            // is the only place a windowed binary can say which half went
            // wrong — the window not opening, or the page not being asked for.
            tracing::info!("showing the settings");
            html(StatusCode::OK, view(handle, None, None))
        }
        ("POST", "/save") => save(handle, request.body()),
        (method, path) => {
            tracing::warn!(method, path, "no such settings page");
            plain(StatusCode::NOT_FOUND, "No such page.")
        }
    }
}

/// Take what the form said, and act on it.
fn save(handle: &AppHandle, body: &[u8]) -> Response<Cow<'static, [u8]>> {
    let chosen = match read_form(body) {
        Ok(chosen) => chosen,
        Err(complaint) => {
            tracing::warn!(complaint, "the settings form was not usable");
            return html(
                StatusCode::BAD_REQUEST,
                view(handle, None, Some(&complaint)),
            );
        }
    };

    tracing::info!(port = ?chosen.port(), "the settings were submitted");

    let mut stored = settings::load(handle);

    // Saying the same thing again is not a reason to restart, and a restart
    // nobody asked for looks like a crash that recovered.
    if stored.port == chosen.port() {
        close_later(handle);
        return html(
            StatusCode::OK,
            done(
                "Nothing to change",
                "That is what Rhizolog is already doing.",
            ),
        );
    }

    stored.port = chosen.port();
    if let Err(error) = settings::save(handle, &stored) {
        tracing::error!("{error:#}");
        let complaint = format!("Rhizolog could not save that. {error:#}");
        return html(
            StatusCode::INTERNAL_SERVER_ERROR,
            view(handle, Some(chosen), Some(&complaint)),
        );
    }

    restart_later(handle);
    html(
        StatusCode::OK,
        done("Saved", "Rhizolog is restarting on the new port."),
    )
}

/// What the form asked for.
#[derive(Debug, Clone, Copy, PartialEq, Eq)]
enum Choice {
    /// Prefer 3000, and take any free port when it is busy.
    Automatic,
    /// This port or nothing.
    Fixed(u16),
}

impl Choice {
    fn port(self) -> Option<u16> {
        match self {
            Self::Automatic => None,
            Self::Fixed(port) => Some(port),
        }
    }
}

/// Read the one field the form has.
///
/// Empty means automatic, and that is what lets the form be a single box with
/// no JavaScript behind it. The obvious shape — a pair of radio buttons with a
/// number beside one of them — needs a script to keep the two in step, or it
/// ships the state where somebody has typed a port into a box that is being
/// ignored.
///
/// Nothing is percent-decoded, deliberately. The only value accepted here is a
/// short run of ASCII digits, so anything an encoding could carry fails to
/// parse regardless, and a decoder would be code kept alive for a case that
/// cannot arise.
fn read_form(body: &[u8]) -> Result<Choice, String> {
    let body = std::str::from_utf8(body).map_err(|_| "That form was not text.".to_owned())?;

    let value = body
        .split('&')
        .find_map(|field| field.strip_prefix("port="))
        .ok_or_else(|| "That form had no port in it.".to_owned())?
        .trim();

    if value.is_empty() {
        return Ok(Choice::Automatic);
    }

    match value.parse::<u16>() {
        // Zero is how the OS is asked to pick, which is what leaving the box
        // empty already says — and rather more clearly.
        Ok(0) | Err(_) => Err(format!(
            "{value:?} is not a port. Give a number from 1 to 65535, or leave the box empty."
        )),
        Ok(port) => Ok(Choice::Fixed(port)),
    }
}

/// Close this window, once the response that says so has been sent.
fn close_later(handle: &AppHandle) {
    let handle = handle.clone();
    tauri::async_runtime::spawn(async move {
        if let Some(window) = handle.get_webview_window(LABEL) {
            let _ = window.close();
        }
    });
}

/// Restart, once the response that says so has been sent.
fn restart_later(handle: &AppHandle) {
    let handle = handle.clone();
    tauri::async_runtime::spawn(async move {
        // Stopped properly first, exactly as changing wikis is: a restart that
        // skipped this would lose the last minute of usage counts and leave an
        // endpoint file behind describing a server about to stop existing.
        crate::stop(&handle).await;
        handle.restart();
    });
}

/// What the page has to say about the state of things.
struct View<'a> {
    /// What the port box should show.
    choice: Choice,
    /// Where the server is listening, if it got that far.
    address: Option<SocketAddr>,
    /// `RHIZOLOG_ADDR`'s value, when it is set and therefore deciding.
    forced: Option<String>,
    /// Why the last attempt did not take.
    complaint: Option<&'a str>,
}

fn view(handle: &AppHandle, chosen: Option<Choice>, complaint: Option<&str>) -> Vec<u8> {
    let stored = settings::load(handle);

    let choice = chosen.unwrap_or(match stored.port {
        Some(port) => Choice::Fixed(port),
        None => Choice::Automatic,
    });

    document(&View {
        choice,
        address: serving(handle),
        forced: std::env::var(rhizolog::config::ENV_ADDRESS).ok(),
        complaint,
    })
}

/// The address the server actually bound.
///
/// Read from the running server rather than from the settings, because those
/// are two different questions: the settings say what was asked for, and this
/// says what was got. On a first run with 3000 taken they disagree, and the one
/// worth showing is the one a browser would reach.
fn serving(handle: &AppHandle) -> Option<SocketAddr> {
    handle
        .try_state::<crate::Running>()?
        .0
        .lock()
        .ok()?
        .as_ref()
        .map(Server::address)
}

fn document(view: &View) -> Vec<u8> {
    let serving = match view.address {
        Some(address) => format!("<p class=\"now\">Serving <code>http://{address}</code></p>"),
        None => String::new(),
    };

    let complaint = match view.complaint {
        Some(text) => format!("<p class=\"alarm\">{}</p>", escape(text)),
        None => String::new(),
    };

    // Not the app's decision to make, so not the app's control to offer. The
    // value is shown because "this box does nothing" is a worse thing to
    // discover than to be told.
    let (forced, disabled) = match &view.forced {
        Some(value) => (
            format!(
                "<p class=\"note\"><code>RHIZOLOG_ADDR</code> is set to <code>{}</code>, so it \
                 decides the address and this setting is ignored. Unset it and start Rhizolog \
                 again to choose here.</p>",
                escape(value)
            ),
            " disabled",
        ),
        None => (String::new(), ""),
    };

    let port = match view.choice {
        Choice::Automatic => String::new(),
        Choice::Fixed(port) => port.to_string(),
    };

    let document = format!(
        "<!doctype html>\n\
         <html lang=\"en\">\n\
         <head>\n\
         <meta charset=\"utf-8\">\n\
         <title>Rhizolog Settings</title>\n\
         <style>{STYLE}</style>\n\
         </head>\n\
         <body>\n\
         <main>\n\
         <h1>Settings</h1>\n\
         {serving}\n\
         {complaint}\n\
         <form method=\"post\" action=\"/save\">\n\
         <h2><label for=\"port\">Port</label></h2>\n\
         <p><input type=\"number\" id=\"port\" name=\"port\" min=\"1\" max=\"65535\" \
         placeholder=\"Automatic\" value=\"{port}\" autofocus{disabled}></p>\n\
         <p class=\"note\">Leave it empty to let Rhizolog choose: it takes 3000 when that is \
         free, and any free port when it is not. A port given here is a requirement — Rhizolog \
         will offer to choose one itself rather than start somewhere else.</p>\n\
         {forced}\n\
         <p class=\"actions\"><button type=\"submit\"{disabled}>Save and restart</button></p>\n\
         <p class=\"note\">The server is bound at startup, so changing the port restarts \
         Rhizolog. It reopens the same wiki.</p>\n\
         </form>\n\
         </main>\n\
         </body>\n\
         </html>\n"
    );

    document.into_bytes()
}

/// The page shown after the form has been dealt with.
fn done(heading: &str, detail: &str) -> Vec<u8> {
    format!(
        "<!doctype html>\n\
         <html lang=\"en\">\n\
         <head>\n\
         <meta charset=\"utf-8\">\n\
         <title>Rhizolog Settings</title>\n\
         <style>{STYLE}</style>\n\
         </head>\n\
         <body>\n\
         <main>\n\
         <h1>{}</h1>\n\
         <p class=\"note\">{}</p>\n\
         </main>\n\
         </body>\n\
         </html>\n",
        escape(heading),
        escape(detail),
    )
    .into_bytes()
}

const STYLE: &str = "
:root {
  color-scheme: light dark;
  --ink: #1c1917; --paper: #fafaf9; --quiet: #57534e;
  --line: #d6d3d1; --field: #ffffff; --alarm: #9f1239;
}
@media (prefers-color-scheme: dark) {
  :root {
    --ink: #e7e5e4; --paper: #1c1917; --quiet: #a8a29e;
    --line: #44403c; --field: #292524; --alarm: #fda4af;
  }
}
* { box-sizing: border-box; }
body {
  margin: 0; padding: 26px 30px;
  font: 14px/1.55 'Segoe UI', system-ui, sans-serif;
  color: var(--ink); background: var(--paper);
}
main { max-width: 32rem; }
h1 { font-size: 1.15rem; margin: 0 0 0.35rem; }
h2 { font-size: 0.95rem; margin: 1.5rem 0 0.4rem; }
p { margin: 0 0 0.6rem; }
code { font-family: Consolas, ui-monospace, monospace; font-size: 0.92em; }
.now { color: var(--quiet); margin-bottom: 1rem; }
.note { color: var(--quiet); font-size: 0.9rem; }
.alarm {
  color: var(--alarm); border-left: 3px solid var(--alarm);
  padding: 0.4rem 0.7rem; margin-bottom: 1rem;
}
input[type=number] {
  width: 9rem; padding: 0.4rem 0.55rem;
  font: inherit; color: inherit;
  background: var(--field); border: 1px solid var(--line); border-radius: 4px;
}
.actions { margin-top: 1.4rem; }
button {
  padding: 0.45rem 1rem; font: inherit;
  color: var(--paper); background: var(--ink);
  border: 1px solid var(--ink); border-radius: 4px; cursor: pointer;
}
button:disabled, input:disabled { opacity: 0.5; cursor: default; }
";

/// Everything here is short and most of it is a number, but two of the strings
/// are somebody else's: an environment variable and an error message that
/// quotes what was typed into the box.
fn escape(text: &str) -> String {
    let mut escaped = String::with_capacity(text.len());

    for character in text.chars() {
        match character {
            '&' => escaped.push_str("&amp;"),
            '<' => escaped.push_str("&lt;"),
            '>' => escaped.push_str("&gt;"),
            '"' => escaped.push_str("&quot;"),
            '\'' => escaped.push_str("&#39;"),
            other => escaped.push(other),
        }
    }

    escaped
}

fn html(status: StatusCode, body: Vec<u8>) -> Response<Cow<'static, [u8]>> {
    Response::builder()
        .status(status)
        // The page states the port the server is on, which the form it carries
        // is in the business of changing.
        .header(header::CACHE_CONTROL, "no-store")
        .header(header::CONTENT_TYPE, "text/html; charset=utf-8")
        .body(Cow::Owned(body))
        .expect("a response with a valid status and headers")
}

fn plain(status: StatusCode, body: &'static str) -> Response<Cow<'static, [u8]>> {
    Response::builder()
        .status(status)
        .header(header::CACHE_CONTROL, "no-store")
        .header(header::CONTENT_TYPE, "text/plain; charset=utf-8")
        .body(Cow::Borrowed(body.as_bytes()))
        .expect("a response with a valid status and headers")
}

#[cfg(test)]
mod tests {
    use super::*;

    /// The whole form, and the reason it is one box: nothing typed is a
    /// perfectly ordinary answer rather than a mistake.
    #[test]
    fn an_empty_box_is_automatic() {
        assert_eq!(read_form(b"port="), Ok(Choice::Automatic));
        assert_eq!(read_form(b"port=  "), Ok(Choice::Automatic));
    }

    #[test]
    fn a_number_is_a_port() {
        assert_eq!(read_form(b"port=8080"), Ok(Choice::Fixed(8080)));
        assert_eq!(read_form(b"port=1"), Ok(Choice::Fixed(1)));
        assert_eq!(read_form(b"port=65535"), Ok(Choice::Fixed(65535)));
    }

    /// Every one of these is something a hand-written post could say, and none
    /// of them may become a port the app then fails to bind on every launch.
    #[test]
    fn anything_that_is_not_a_port_is_refused() {
        for body in [
            &b"port=0"[..],
            b"port=65536",
            b"port=-1",
            b"port=3000.5",
            b"port=three thousand",
            b"port=3000%3B",
        ] {
            assert!(
                read_form(body).is_err(),
                "{:?} was accepted",
                String::from_utf8_lossy(body)
            );
        }
    }

    #[test]
    fn a_form_without_a_port_is_refused() {
        assert!(read_form(b"").is_err());
        assert!(read_form(b"wiki_root=%2Ftmp").is_err());
    }

    /// The field is found by name rather than by position, because a browser
    /// orders a form's fields however it likes and this one will grow.
    #[test]
    fn the_port_is_found_among_other_fields() {
        assert_eq!(read_form(b"other=1&port=8080"), Ok(Choice::Fixed(8080)));
        assert_eq!(read_form(b"port=8080&other=1"), Ok(Choice::Fixed(8080)));
    }

    /// What is stored is `None` for automatic, which is what
    /// [`crate::listen_for`] turns back into a preference rather than a
    /// requirement.
    #[test]
    fn automatic_is_stored_as_nothing() {
        assert_eq!(Choice::Automatic.port(), None);
        assert_eq!(Choice::Fixed(8080).port(), Some(8080));
    }

    /// A window label has to be unique, and a settings window that collided
    /// with a page window would simply fail to open.
    #[test]
    fn the_label_cannot_collide_with_a_page_window() {
        assert_ne!(LABEL, "main");
        assert!(!crate::label_for(&url()).starts_with(LABEL));
    }

    /// `RHIZOLOG_ADDR` is printed into the page, and it is a string from
    /// outside the app.
    #[test]
    fn the_page_escapes_what_it_did_not_write() {
        let page = String::from_utf8(document(&View {
            choice: Choice::Fixed(8080),
            address: None,
            forced: Some("<script>alert(1)</script>".to_owned()),
            complaint: Some("\"quoted\" & <angled>"),
        }))
        .expect("the page is utf-8");

        assert!(!page.contains("<script>"), "{page}");
        assert!(page.contains("&lt;script&gt;"));
        assert!(page.contains("&quot;quoted&quot; &amp; &lt;angled&gt;"));
    }

    /// The value has to survive into the box, or opening the window would look
    /// like the setting had been forgotten.
    #[test]
    fn the_page_shows_the_port_it_was_given() {
        let page = String::from_utf8(document(&View {
            choice: Choice::Fixed(8080),
            address: "127.0.0.1:8080".parse().ok(),
            forced: None,
            complaint: None,
        }))
        .expect("the page is utf-8");

        assert!(page.contains("value=\"8080\""), "{page}");
        assert!(page.contains("http://127.0.0.1:8080"));
        // The attribute rather than the word: the stylesheet has `:disabled`
        // rules in it either way.
        assert!(page.contains("autofocus>"), "the box is usable");
        assert!(
            page.contains("<button type=\"submit\">"),
            "so is the button"
        );
    }

    /// A control that cannot be honoured is worse than one that is not offered,
    /// so the environment switches the form off rather than letting somebody
    /// save a setting that will be ignored.
    #[test]
    fn the_environment_disables_the_form() {
        let page = String::from_utf8(document(&View {
            choice: Choice::Automatic,
            address: None,
            forced: Some("127.0.0.1:9999".to_owned()),
            complaint: None,
        }))
        .expect("the page is utf-8");

        assert!(page.contains("<button type=\"submit\" disabled>"), "{page}");
        assert!(page.contains("autofocus disabled>"));
        assert!(
            page.contains("value=\"\""),
            "automatic leaves the box empty"
        );
    }
}
